# Site settings
baseurl = "https://portfolio.m4ck3ngm.com/"
languageCode = "en-us"
title = "Hugo Artists Theme"
theme = "hugo-artists-theme"
canonifyurls = true

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Mackenzie McFate"
	description = "Hungry for knowledge."

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "m4ck3ngm@gmail.com"


	# Header an navigation
	#
	# To change the header background the 'hero-bg-jpg' at 'static/img'.
	# Do the same with the logo ('logo.svg').
	# But keep the original filename!
	[params.header]
		title = "Mackenzie McFate"
		shortBio = "Ready when you are."


	# About section
	#
	# Replace the 'avatar.jpg' under 'static/img' with your own image.
	[params.about]
		title = "About"
		bio = "**Grinnell College Computer Science graduate.** Not exactly a blank slate, but there's plenty of room on the slate nonetheless."

		[[params.about.skills]]
			name = "Java"
			value = 8

		[[params.about.skills]]
			name = "C"
			value = 9

		[[params.about.skills]]
			name = "C++"
			value = 7

		[[params.about.skills]]
			name = "Ruby"
			value = 2

		[[params.about.skills]]
			name = "Python"
			value = 7

		[[params.about.skills]]
			name = "Scheme"
			value = 8

	# Contact secion
	[params.contact]
		title = "Contact"

		# The following social network icons are available:
		# 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin'
		# 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
		[[params.contact.social]]
			icon = "twitter"
			link = "//twitter.com/M4CK3NGM"

		#[[params.contact.social]]
		#	icon = "dribbble"
		#	link = "//dribbble.com/"

		[[params.contact.social]]
			icon = "instagram"
			link = "//www.instagram.com/m4ck3ngm"

		#[[params.contact.social]]
		#	icon = "youtube"
		#	link = "//www.youtube.com/"

		[[params.contact.social]]
			icon = "linkedin"
			link = "//www.linkedin.com/in/mackenzie-mcfate-4a1062156/?trk=onboarding-landing&dl=no"


	[params.form]
		title = ""
		# Form fields
		name = "Your Name"
		email = "Your Email"
		message = "Questions?"
		buttonText = "Send"


	[params.footer]
		copyright = "Published under the Unlicense License."
